// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3757361161807749610),
      name: 'SudokuStat',
      lastPropertyId: const obx_int.IdUid(5, 7304686081228087153),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5371859328587730539),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3363495232771419351),
            name: 'time',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3076829879382317897),
            name: 'level',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8868486448329788345),
            name: 'result',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7304686081228087153),
            name: 'timeMode',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 3757361161807749610),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SudokuStat: obx_int.EntityDefinition<SudokuStat>(
        model: _entities[0],
        toOneRelations: (SudokuStat object) => [],
        toManyRelations: (SudokuStat object) => {},
        getId: (SudokuStat object) => object.id,
        setId: (SudokuStat object, int id) {
          object.id = id;
        },
        objectToFB: (SudokuStat object, fb.Builder fbb) {
          final levelOffset = fbb.writeString(object.level);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.time);
          fbb.addOffset(2, levelOffset);
          fbb.addInt64(3, object.result);
          fbb.addInt64(4, object.timeMode);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final timeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final levelParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final resultParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final timeModeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = SudokuStat(
              id: idParam,
              time: timeParam,
              level: levelParam,
              result: resultParam,
              timeMode: timeModeParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SudokuStat] entity fields to define ObjectBox queries.
class SudokuStat_ {
  /// See [SudokuStat.id].
  static final id =
      obx.QueryIntegerProperty<SudokuStat>(_entities[0].properties[0]);

  /// See [SudokuStat.time].
  static final time =
      obx.QueryIntegerProperty<SudokuStat>(_entities[0].properties[1]);

  /// See [SudokuStat.level].
  static final level =
      obx.QueryStringProperty<SudokuStat>(_entities[0].properties[2]);

  /// See [SudokuStat.result].
  static final result =
      obx.QueryIntegerProperty<SudokuStat>(_entities[0].properties[3]);

  /// See [SudokuStat.timeMode].
  static final timeMode =
      obx.QueryIntegerProperty<SudokuStat>(_entities[0].properties[4]);
}
